version: '3'

services:
  pets-and-paws-db:
    image: postgres:14
    container_name: pets-and-paws-db
    ports:
      - "5432:5432"
    volumes:
      - pets-and-paws-data:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=admin123

volumes:
  pets-and-paws-data: