version: '3'

services:
  pets-and-paws-db:
    image: postgres:14
    container_name: pets-and-paws-db
    ports:
      - "5432:5432"
    volumes:
      - pets-and-paws-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=pets-and-paws
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123

  pets-and-paws-api:
    image: pets-and-paws-api
    container_name: pets-and-paws-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - pets-and-paws-db
    environment:
      - DatabaseSettings__Connections__Postgres=Host=pets-and-paws-db;Port=5432;Database=pets-and-paws;Username=postgres;Password=admin123

volumes:
  pets-and-paws-data: